version: '3.8'

services:
  app:
    build:
      context: .
    restart: always
    networks:
      - local_network
    ports:
      - "8080"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 1234
    networks:
      - local_network
    ports:
      - "3306:3306"

networks:
  local_network:
    driver: bridge